#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BaseHumanAnimBP_Fists_Female

#include "Basic.hpp"

#include "BaseHumanAnimBP_Fists_Female_classes.hpp"


namespace SDK
{

// Function BaseHumanAnimBP_Fists_Female.BaseHumanAnimBP_Fists_Female_C.UpdateLayeringValues
// (Public, BlueprintCallable, BlueprintEvent)

void UBaseHumanAnimBP_Fists_Female_C::UpdateLayeringValues()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BaseHumanAnimBP_Fists_Female_C", "UpdateLayeringValues");

	UObject::ProcessEvent(Func, nullptr);
}

}

