#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BaseHumanAnimBP_CC_Female

#include "Basic.hpp"

#include "BaseHumanAnimBP_Fists_structs.hpp"


namespace SDK
{

// ScriptStruct BaseHumanAnimBP_CC_Female.BaseHumanAnimBP_CC_Female_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0xC570 - 0xC570)
struct BaseHumanAnimBP_CC_Female::FAnimBlueprintGeneratedConstantData final : public BaseHumanAnimBP_Fists::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_BaseHumanAnimBP_CC_Female__FAnimBlueprintGeneratedConstantData;

}

