#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Bot_Interface

#include "Basic.hpp"


namespace SDK::Params
{

// Function Bot_Interface.Bot_Interface_C.GetTauntMontages
// 0x0020 (0x0020 - 0x0000)
struct Bot_Interface_C_GetTauntMontages final
{
public:
	TArray<class UAnimMontage*>                   Taunts;                                            // 0x0000(0x0010)(Parm, OutParm)
	TArray<class UAnimMontage*>                   AltTaunts;                                         // 0x0010(0x0010)(Parm, OutParm)
};
DUMPER7_ASSERTS_Bot_Interface_C_GetTauntMontages;

// Function Bot_Interface.Bot_Interface_C.IsUsingAltSkeletalMesh
// 0x0001 (0x0001 - 0x0000)
struct Bot_Interface_C_IsUsingAltSkeletalMesh final
{
public:
	bool                                          Ret;                                               // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Bot_Interface_C_IsUsingAltSkeletalMesh;

// Function Bot_Interface.Bot_Interface_C.PlayTauntMontage
// 0x0008 (0x0008 - 0x0000)
struct Bot_Interface_C_PlayTauntMontage final
{
public:
	double                                        Ret;                                               // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Bot_Interface_C_PlayTauntMontage;

}

