#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_CustomComboBoxInterface

#include "Basic.hpp"

#include "BPI_CustomComboBoxInterface_classes.hpp"
#include "BPI_CustomComboBoxInterface_parameters.hpp"


namespace SDK
{

// Function BPI_CustomComboBoxInterface.BPI_CustomComboBoxInterface_C.OnOptionSelectedInterface
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    Option                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   ID                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IBPI_CustomComboBoxInterface_C::OnOptionSelectedInterface(const class FString& Option, int64 ID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_CustomComboBoxInterface_C", "OnOptionSelectedInterface");

	Params::BPI_CustomComboBoxInterface_C_OnOptionSelectedInterface Parms{};

	Parms.Option = std::move(Option);
	Parms.ID = ID;

	AsUObject()->ProcessEvent(Func, &Parms);
}

}

