#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CFCoreUIWidget

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"
#include "Engine_structs.hpp"
#include "Struct_CfcoreUITheme_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CFCoreUIWidget.CFCoreUIWidget_C
// 0x0080 (0x0838 - 0x07B8)
class UCFCoreUIWidget_C : public UPrimalUI
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x07B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FStruct_CfcoreUITheme                  CFcoreUITheme;                                     // 0x07C0(0x0078)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void ApplyThemeSettingsToAll();
	void ExecuteUbergraph_CFCoreUIWidget(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CFCoreUIWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CFCoreUIWidget_C")
	}
	static class UCFCoreUIWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCFCoreUIWidget_C>();
	}
};
DUMPER7_ASSERTS_UCFCoreUIWidget_C;

}

