#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DataflowSimulation

#include "Basic.hpp"


namespace SDK::Params
{

// Function DataflowSimulation.DataflowSimulationActor.PostDataflowSimulationTick
// 0x0008 (0x0008 - 0x0000)
struct DataflowSimulationActor_PostDataflowSimulationTick final
{
public:
	float                                         SimulationTime;                                    // 0x0000(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DeltaTime;                                         // 0x0004(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DataflowSimulationActor_PostDataflowSimulationTick;

// Function DataflowSimulation.DataflowSimulationActor.PreDataflowSimulationTick
// 0x0008 (0x0008 - 0x0000)
struct DataflowSimulationActor_PreDataflowSimulationTick final
{
public:
	float                                         SimulationTime;                                    // 0x0000(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DeltaTime;                                         // 0x0004(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DataflowSimulationActor_PreDataflowSimulationTick;

}

