#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngramEntry_HazardSuit_Chest

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EngramEntry_HazardSuit_Chest.EngramEntry_HazardSuit_Chest_C
// 0x0000 (0x00A0 - 0x00A0)
class UEngramEntry_HazardSuit_Chest_C final : public UPrimalEngramEntry
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EngramEntry_HazardSuit_Chest_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"EngramEntry_HazardSuit_Chest_C")
	}
	static class UEngramEntry_HazardSuit_Chest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngramEntry_HazardSuit_Chest_C>();
	}
};
DUMPER7_ASSERTS_UEngramEntry_HazardSuit_Chest_C;

}

