#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FPVClimbPickHitCameraShake

#include "Basic.hpp"

#include "EngineCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FPVClimbPickHitCameraShake.FPVClimbPickHitCameraShake_C
// 0x0000 (0x0200 - 0x0200)
class UFPVClimbPickHitCameraShake_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("FPVClimbPickHitCameraShake_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FPVClimbPickHitCameraShake_C")
	}
	static class UFPVClimbPickHitCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFPVClimbPickHitCameraShake_C>();
	}
};
DUMPER7_ASSERTS_UFPVClimbPickHitCameraShake_C;

}

