#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HudOverlayUITop

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass HudOverlayUITop.HudOverlayUITop_C
// 0x0008 (0x07E8 - 0x07E0)
class UHudOverlayUITop_C final : public UUI_HudOverlay
{
public:
	class UHUDOVerlayWidget*                      HudOverlay;                                        // 0x07E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HudOverlayUITop_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HudOverlayUITop_C")
	}
	static class UHudOverlayUITop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHudOverlayUITop_C>();
	}
};
DUMPER7_ASSERTS_UHudOverlayUITop_C;

}

