#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Human_Female_TPV_PPAnimBP_Child

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Human_Male_TPV_PPAnimBP_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Human_Female_TPV_PPAnimBP_Child.Human_Female_TPV_PPAnimBP_Child_C
// 0x0010 (0x1480 - 0x1470)
class UHuman_Female_TPV_PPAnimBP_Child_C final : public UHuman_Male_TPV_PPAnimBP_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Human_Female_TPV_PPAnimBP_Child_C;  // 0x1470(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void ExecuteUbergraph_Human_Female_TPV_PPAnimBP_Child(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Human_Female_TPV_PPAnimBP_Child_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Human_Female_TPV_PPAnimBP_Child_C")
	}
	static class UHuman_Female_TPV_PPAnimBP_Child_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHuman_Female_TPV_PPAnimBP_Child_C>();
	}
};
DUMPER7_ASSERTS_UHuman_Female_TPV_PPAnimBP_Child_C;

}

