#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenuGameMode

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MainMenuGameMode.MainMenuGameMode_C
// 0x0008 (0x0610 - 0x0608)
class AMainMenuGameMode_C final : public AShooterGame_Menu
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0608(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MainMenuGameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MainMenuGameMode_C")
	}
	static class AMainMenuGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMainMenuGameMode_C>();
	}
};
DUMPER7_ASSERTS_AMainMenuGameMode_C;

}

