#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeshFadeOut_Blueprint_Fast_WithDrop

#include "Basic.hpp"

#include "MeshFadeOut_Blueprint_WithDrop_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MeshFadeOut_Blueprint_Fast_WithDrop.MeshFadeOut_Blueprint_Fast_WithDrop_C
// 0x0000 (0x0510 - 0x0510)
class AMeshFadeOut_Blueprint_Fast_WithDrop_C final : public AMeshFadeOut_Blueprint_WithDrop_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MeshFadeOut_Blueprint_Fast_WithDrop_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MeshFadeOut_Blueprint_Fast_WithDrop_C")
	}
	static class AMeshFadeOut_Blueprint_Fast_WithDrop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMeshFadeOut_Blueprint_Fast_WithDrop_C>();
	}
};
DUMPER7_ASSERTS_AMeshFadeOut_Blueprint_Fast_WithDrop_C;

}

