#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModelingOperators

#include "Basic.hpp"


namespace SDK::Params
{

// Function ModelingOperators.UVEditorTexelDensitySettings.InSamplingMode
// 0x0001 (0x0001 - 0x0000)
struct UVEditorTexelDensitySettings_InSamplingMode final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_UVEditorTexelDensitySettings_InSamplingMode;

}

