#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumable_CureLow

#include "Basic.hpp"

#include "PrimalItemConsumableGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemConsumable_CureLow.PrimalItemConsumable_CureLow_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemConsumable_CureLow_C final : public UPrimalItemConsumableGeneric_C
{
public:
	uint8                                         Pad_B53[0x5];                                      // 0x0B53(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimalItem*                            SelfObj;                                           // 0x0B58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BlueprintUsed();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemConsumable_CureLow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemConsumable_CureLow_C")
	}
	static class UPrimalItemConsumable_CureLow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemConsumable_CureLow_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemConsumable_CureLow_C;

}

