#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemResource_SquidOil

#include "Basic.hpp"

#include "PrimalItemResource_Oil_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemResource_SquidOil.PrimalItemResource_SquidOil_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemResource_SquidOil_C final : public UPrimalItemResource_Oil_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemResource_SquidOil_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemResource_SquidOil_C")
	}
	static class UPrimalItemResource_SquidOil_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemResource_SquidOil_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemResource_SquidOil_C;

}

