#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumable_HemogoblinCocktail_ASA

#include "Basic.hpp"

#include "PrimalItemConsumableGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemConsumable_HemogoblinCocktail_ASA.PrimalItemConsumable_HemogoblinCocktail_ASA_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemConsumable_HemogoblinCocktail_ASA_C final : public UPrimalItemConsumableGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemConsumable_HemogoblinCocktail_ASA_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemConsumable_HemogoblinCocktail_ASA_C")
	}
	static class UPrimalItemConsumable_HemogoblinCocktail_ASA_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemConsumable_HemogoblinCocktail_ASA_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemConsumable_HemogoblinCocktail_ASA_C;

}

