#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_TekShirt_Gen2

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "PrimalItemArmor_TekShirt_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemArmor_TekShirt_Gen2.PrimalItemArmor_TekShirt_Gen2_C
// 0x0060 (0x0C30 - 0x0BD0)
class UPrimalItemArmor_TekShirt_Gen2_C final : public UPrimalItemArmor_TekShirt_C
{
public:
	struct FTransform                             TekSuitVFXOffset;                                  // 0x0BD0(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ApplyingSkinOntoItem(class UPrimalItem* ToOwnerItem, bool bIsFirstTime);
	void BlueprintEquipped(bool bIsFromSaveGame);
	void BlueprintUnequipped();
	void RemovedSkinFromItem(class UPrimalItem* FromOwnerItem, bool bIsFirstTime);
	void TryTekSuitVFXOffset(bool IsUnequip);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_TekShirt_Gen2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemArmor_TekShirt_Gen2_C")
	}
	static class UPrimalItemArmor_TekShirt_Gen2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_TekShirt_Gen2_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemArmor_TekShirt_Gen2_C;

}

