#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_ScubaBoots_Flippers

#include "Basic.hpp"

#include "PrimalItemArmor_BaseBoots_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemArmor_ScubaBoots_Flippers.PrimalItemArmor_ScubaBoots_Flippers_C
// 0x0020 (0x0B80 - 0x0B60)
class UPrimalItemArmor_ScubaBoots_Flippers_C final : public UPrimalItemArmor_BaseBoots_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0B60(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UClass*                                 EquippedBuff;                                      // 0x0B68(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UPrimalItem*                            SelfObj;                                           // 0x0B70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BlueprintEquipped(bool bIsFromSaveGame);
	void BlueprintUnequipped();
	void ExecuteUbergraph_PrimalItemArmor_ScubaBoots_Flippers(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_ScubaBoots_Flippers_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemArmor_ScubaBoots_Flippers_C")
	}
	static class UPrimalItemArmor_ScubaBoots_Flippers_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_ScubaBoots_Flippers_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemArmor_ScubaBoots_Flippers_C;

}

