#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_TekBoots

#include "Basic.hpp"

#include "PrimalItemArmor_Base_Tek_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemArmor_TekBoots.PrimalItemArmor_TekBoots_C
// 0x0000 (0x0BC0 - 0x0BC0)
class UPrimalItemArmor_TekBoots_C : public UPrimalItemArmor_Base_Tek_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_TekBoots_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemArmor_TekBoots_C")
	}
	static class UPrimalItemArmor_TekBoots_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_TekBoots_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemArmor_TekBoots_C;

}

