#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_WeaponHandcuffs

#include "Basic.hpp"

#include "PrimalItem_WeaponBaseHatchet_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItem_WeaponHandcuffs.PrimalItem_WeaponHandcuffs_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItem_WeaponHandcuffs_C final : public UPrimalItem_WeaponBaseHatchet_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItem_WeaponHandcuffs_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItem_WeaponHandcuffs_C")
	}
	static class UPrimalItem_WeaponHandcuffs_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_WeaponHandcuffs_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItem_WeaponHandcuffs_C;

}

