#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_BaseCliffPlatform

#include "Basic.hpp"

#include "PrimalItemStructure_BaseCeiling_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_BaseCliffPlatform.PrimalItemStructure_BaseCliffPlatform_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemStructure_BaseCliffPlatform_C : public UPrimalItemStructure_BaseCeiling_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_BaseCliffPlatform_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemStructure_BaseCliffPlatform_C")
	}
	static class UPrimalItemStructure_BaseCliffPlatform_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_BaseCliffPlatform_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemStructure_BaseCliffPlatform_C;

}

