#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_GreenhouseRoof

#include "Basic.hpp"

#include "PrimalItemStructure_BaseRoof_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_GreenhouseRoof.PrimalItemStructure_GreenhouseRoof_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemStructure_GreenhouseRoof_C final : public UPrimalItemStructure_BaseRoof_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_GreenhouseRoof_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemStructure_GreenhouseRoof_C")
	}
	static class UPrimalItemStructure_GreenhouseRoof_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_GreenhouseRoof_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemStructure_GreenhouseRoof_C;

}

