#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_StoneGate

#include "Basic.hpp"

#include "PrimalItemStructure_BaseGate_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_StoneGate.PrimalItemStructure_StoneGate_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemStructure_StoneGate_C final : public UPrimalItemStructure_BaseGate_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_StoneGate_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemStructure_StoneGate_C")
	}
	static class UPrimalItemStructure_StoneGate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_StoneGate_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemStructure_StoneGate_C;

}

