#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemResource_RedSap

#include "Basic.hpp"

#include "PrimalItemResource_Gem_Element_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemResource_RedSap.PrimalItemResource_RedSap_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemResource_RedSap_C final : public UPrimalItemResource_Gem_Element_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemResource_RedSap_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemResource_RedSap_C")
	}
	static class UPrimalItemResource_RedSap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemResource_RedSap_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemResource_RedSap_C;

}

