#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemSkin_CharacterSkin_Base

#include "Basic.hpp"

#include "PrimalItemSkinGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemSkin_CharacterSkin_Base.PrimalItemSkin_CharacterSkin_Base_C
// 0x0000 (0x0B70 - 0x0B70)
#pragma pack(push, 0x1)
class alignas(0x10) UPrimalItemSkin_CharacterSkin_Base_C : public UPrimalItemSkinGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemSkin_CharacterSkin_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemSkin_CharacterSkin_Base_C")
	}
	static class UPrimalItemSkin_CharacterSkin_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemSkin_CharacterSkin_Base_C>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_UPrimalItemSkin_CharacterSkin_Base_C;

}

