#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemSkin_RustlerPants

#include "Basic.hpp"

#include "PrimalItemSkinGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemSkin_RustlerPants.PrimalItemSkin_RustlerPants_C
// 0x0000 (0x0B70 - 0x0B70)
class UPrimalItemSkin_RustlerPants_C final : public UPrimalItemSkinGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemSkin_RustlerPants_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemSkin_RustlerPants_C")
	}
	static class UPrimalItemSkin_RustlerPants_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemSkin_RustlerPants_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemSkin_RustlerPants_C;

}

