#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumable_Fertilizer_BatGuano

#include "Basic.hpp"

#include "PrimalItemConsumable_Fertilizer_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemConsumable_Fertilizer_BatGuano.PrimalItemConsumable_Fertilizer_BatGuano_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemConsumable_Fertilizer_BatGuano_C final : public UPrimalItemConsumable_Fertilizer_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemConsumable_Fertilizer_BatGuano_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemConsumable_Fertilizer_BatGuano_C")
	}
	static class UPrimalItemConsumable_Fertilizer_BatGuano_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemConsumable_Fertilizer_BatGuano_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemConsumable_Fertilizer_BatGuano_C;

}

