#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemSkin_Thrall_T3_Shirt_Cape

#include "Basic.hpp"

#include "PrimalItemArmor_BaseAccessory_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemSkin_Thrall_T3_Shirt_Cape.PrimalItemSkin_Thrall_T3_Shirt_Cape_C
// 0x0000 (0x0BC0 - 0x0BC0)
class UPrimalItemSkin_Thrall_T3_Shirt_Cape_C final : public UPrimalItemArmor_BaseAccessory_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemSkin_Thrall_T3_Shirt_Cape_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemSkin_Thrall_T3_Shirt_Cape_C")
	}
	static class UPrimalItemSkin_Thrall_T3_Shirt_Cape_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemSkin_Thrall_T3_Shirt_Cape_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemSkin_Thrall_T3_Shirt_Cape_C;

}

