#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_TriFoundation_Thatch

#include "Basic.hpp"

#include "PrimalItemStructure_BaseFloor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_TriFoundation_Thatch.PrimalItemStructure_TriFoundation_Thatch_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemStructure_TriFoundation_Thatch_C final : public UPrimalItemStructure_BaseFloor_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_TriFoundation_Thatch_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemStructure_TriFoundation_Thatch_C")
	}
	static class UPrimalItemStructure_TriFoundation_Thatch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_TriFoundation_Thatch_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemStructure_TriFoundation_Thatch_C;

}

