#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_WeaponC4

#include "Basic.hpp"

#include "PrimalItemWeaponGenericNoStats_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItem_WeaponC4.PrimalItem_WeaponC4_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItem_WeaponC4_C final : public UPrimalItemWeaponGenericNoStats_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItem_WeaponC4_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItem_WeaponC4_C")
	}
	static class UPrimalItem_WeaponC4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_WeaponC4_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItem_WeaponC4_C;

}

