#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_AdobeCeiling

#include "Basic.hpp"

#include "PrimalItemStructure_BaseCeiling_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_AdobeCeiling.PrimalItemStructure_AdobeCeiling_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemStructure_AdobeCeiling_C final : public UPrimalItemStructure_BaseCeiling_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_AdobeCeiling_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemStructure_AdobeCeiling_C")
	}
	static class UPrimalItemStructure_AdobeCeiling_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_AdobeCeiling_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemStructure_AdobeCeiling_C;

}

