#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_GachaSaddle

#include "Basic.hpp"

#include "PrimalItemArmor_SaddleGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemArmor_GachaSaddle.PrimalItemArmor_GachaSaddle_C
// 0x0000 (0x0B80 - 0x0B80)
class UPrimalItemArmor_GachaSaddle_C final : public UPrimalItemArmor_SaddleGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_GachaSaddle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemArmor_GachaSaddle_C")
	}
	static class UPrimalItemArmor_GachaSaddle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_GachaSaddle_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemArmor_GachaSaddle_C;

}

