#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemWeapon_StoresCharge

#include "Basic.hpp"

#include "PrimalItemWeaponGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemWeapon_StoresCharge.PrimalItemWeapon_StoresCharge_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemWeapon_StoresCharge_C : public UPrimalItemWeaponGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemWeapon_StoresCharge_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemWeapon_StoresCharge_C")
	}
	static class UPrimalItemWeapon_StoresCharge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemWeapon_StoresCharge_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemWeapon_StoresCharge_C;

}

