#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumable_Berry_Verdberry

#include "Basic.hpp"

#include "PrimalItemConsumable_Berry_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemConsumable_Berry_Verdberry.PrimalItemConsumable_Berry_Verdberry_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemConsumable_Berry_Verdberry_C final : public UPrimalItemConsumable_Berry_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemConsumable_Berry_Verdberry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemConsumable_Berry_Verdberry_C")
	}
	static class UPrimalItemConsumable_Berry_Verdberry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemConsumable_Berry_Verdberry_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemConsumable_Berry_Verdberry_C;

}

