#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_ThatchWall

#include "Basic.hpp"

#include "PrimalItemStructure_BaseWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_ThatchWall.PrimalItemStructure_ThatchWall_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemStructure_ThatchWall_C final : public UPrimalItemStructure_BaseWall_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_ThatchWall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemStructure_ThatchWall_C")
	}
	static class UPrimalItemStructure_ThatchWall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_ThatchWall_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemStructure_ThatchWall_C;

}

