#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemSkin_DodorexMask

#include "Basic.hpp"

#include "PrimalItemSkinGeneric_Trophy_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemSkin_DodorexMask.PrimalItemSkin_DodorexMask_C
// 0x0000 (0x0B70 - 0x0B70)
class UPrimalItemSkin_DodorexMask_C final : public UPrimalItemSkinGeneric_Trophy_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemSkin_DodorexMask_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemSkin_DodorexMask_C")
	}
	static class UPrimalItemSkin_DodorexMask_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemSkin_DodorexMask_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemSkin_DodorexMask_C;

}

