#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_BearTrap_Large

#include "Basic.hpp"

#include "PrimalItemStructureGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_BearTrap_Large.PrimalItemStructure_BearTrap_Large_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemStructure_BearTrap_Large_C final : public UPrimalItemStructureGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_BearTrap_Large_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemStructure_BearTrap_Large_C")
	}
	static class UPrimalItemStructure_BearTrap_Large_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_BearTrap_Large_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemStructure_BearTrap_Large_C;

}

