#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemRaft

#include "Basic.hpp"

#include "PrimalItem_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemRaft.PrimalItemRaft_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemRaft_C final : public UPrimalItem_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemRaft_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemRaft_C")
	}
	static class UPrimalItemRaft_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemRaft_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemRaft_C;

}

