#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_DinoCompanion_Gear_OxygenTank

#include "Basic.hpp"


namespace SDK::Params
{

// Function PrimalItemArmor_DinoCompanion_Gear_OxygenTank.PrimalItemArmor_DinoCompanion_Gear_OxygenTank_C.ExecuteUbergraph_PrimalItemArmor_DinoCompanion_Gear_OxygenTank
// 0x0008 (0x0008 - 0x0000)
struct PrimalItemArmor_DinoCompanion_Gear_OxygenTank_C_ExecuteUbergraph_PrimalItemArmor_DinoCompanion_Gear_OxygenTank final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_PrimalItemArmor_DinoCompanion_Gear_OxygenTank_C_ExecuteUbergraph_PrimalItemArmor_DinoCompanion_Gear_OxygenTank;

}

