#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_ArgentavisSaddle

#include "Basic.hpp"

#include "PrimalItemArmor_SaddleGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemArmor_ArgentavisSaddle.PrimalItemArmor_ArgentavisSaddle_C
// 0x0000 (0x0B80 - 0x0B80)
class UPrimalItemArmor_ArgentavisSaddle_C final : public UPrimalItemArmor_SaddleGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_ArgentavisSaddle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemArmor_ArgentavisSaddle_C")
	}
	static class UPrimalItemArmor_ArgentavisSaddle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_ArgentavisSaddle_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemArmor_ArgentavisSaddle_C;

}

