#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_RopeLadder

#include "Basic.hpp"

#include "PrimalItemStructure_BaseLadder_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_RopeLadder.PrimalItemStructure_RopeLadder_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemStructure_RopeLadder_C final : public UPrimalItemStructure_BaseLadder_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_RopeLadder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemStructure_RopeLadder_C")
	}
	static class UPrimalItemStructure_RopeLadder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_RopeLadder_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemStructure_RopeLadder_C;

}

