#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_WeaponBaseClipboardAndHammer

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "PrimalItemWeaponGenericAmmoless_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItem_WeaponBaseClipboardAndHammer.PrimalItem_WeaponBaseClipboardAndHammer_C
// 0x00C0 (0x0C20 - 0x0B60)
class UPrimalItem_WeaponBaseClipboardAndHammer_C final : public UPrimalItemWeaponGenericAmmoless_C
{
public:
	uint8                                         Pad_B53[0xD];                                      // 0x0B53(0x000D)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             PreviewHammerTransform;                            // 0x0B60(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             PreviewClipboardTransform;                         // 0x0BC0(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool BPOverridePreviewTransform(class USceneComponent* Comp, struct FTransform* NewTransform);
	bool BPPreventEquip(class UPrimalInventoryComponent* ToInventory);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItem_WeaponBaseClipboardAndHammer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItem_WeaponBaseClipboardAndHammer_C")
	}
	static class UPrimalItem_WeaponBaseClipboardAndHammer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_WeaponBaseClipboardAndHammer_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItem_WeaponBaseClipboardAndHammer_C;

}

