#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_ZiplineMotor

#include "Basic.hpp"

#include "PrimalItemArmor_BaseAccessory_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemArmor_ZiplineMotor.PrimalItemArmor_ZiplineMotor_C
// 0x0020 (0x0BE0 - 0x0BC0)
class UPrimalItemArmor_ZiplineMotor_C final : public UPrimalItemArmor_BaseAccessory_C
{
public:
	double                                        MaxGasoline;                                       // 0x0BC0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimalItem*                            ParentItem;                                        // 0x0BC8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class UTexture2D*>                     MaskTextures;                                      // 0x0BD0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ApplyingSkinOntoItem(class UPrimalItem* ToOwnerItem, bool bIsFirstTime);
	void BlueprintEquipped(bool bIsFromSaveGame);
	void BlueprintUnequipped();
	class FString BPGetCustomInventoryWidgetText();
	class FString BPGetSkinnedCustomInventoryWidgetText();
	void BPInitFromItemNetInfo();
	void EquippedBlueprintTick(float DeltaSeconds);
	bool GetGasolineValueFromItem(class UPrimalItem* TargetItem, double* Value);
	void RemovedSkinFromItem(class UPrimalItem* FromOwnerItem, bool bIsFirstTime);
	void SetGasolineDescription(class UPrimalItem* Item, double Value);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_ZiplineMotor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemArmor_ZiplineMotor_C")
	}
	static class UPrimalItemArmor_ZiplineMotor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_ZiplineMotor_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemArmor_ZiplineMotor_C;

}

