#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemCostume_BionicMosa

#include "Basic.hpp"

#include "PrimalItemCostumeGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemCostume_BionicMosa.PrimalItemCostume_BionicMosa_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemCostume_BionicMosa_C final : public UPrimalItemCostumeGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemCostume_BionicMosa_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemCostume_BionicMosa_C")
	}
	static class UPrimalItemCostume_BionicMosa_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemCostume_BionicMosa_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemCostume_BionicMosa_C;

}

