#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemAmmo_CannonShell

#include "Basic.hpp"

#include "PrimalItemAmmo_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemAmmo_CannonShell.PrimalItemAmmo_CannonShell_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemAmmo_CannonShell_C final : public UPrimalItemAmmo_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemAmmo_CannonShell_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemAmmo_CannonShell_C")
	}
	static class UPrimalItemAmmo_CannonShell_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemAmmo_CannonShell_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemAmmo_CannonShell_C;

}

