#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_WeaponGeneScanner_Base

#include "Basic.hpp"

#include "PrimalItem_WeaponBaseClub_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItem_WeaponGeneScanner_Base.PrimalItem_WeaponGeneScanner_Base_C
// 0x0000 (0x0B60 - 0x0B60)
#pragma pack(push, 0x1)
class alignas(0x10) UPrimalItem_WeaponGeneScanner_Base_C : public UPrimalItem_WeaponBaseClub_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItem_WeaponGeneScanner_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItem_WeaponGeneScanner_Base_C")
	}
	static class UPrimalItem_WeaponGeneScanner_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_WeaponGeneScanner_Base_C>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_UPrimalItem_WeaponGeneScanner_Base_C;

}

