#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemResource_ApexDrop_Argentavis

#include "Basic.hpp"

#include "PrimalItemResourceGeneric_ApexDrop_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemResource_ApexDrop_Argentavis.PrimalItemResource_ApexDrop_Argentavis_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemResource_ApexDrop_Argentavis_C final : public UPrimalItemResourceGeneric_ApexDrop_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemResource_ApexDrop_Argentavis_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemResource_ApexDrop_Argentavis_C")
	}
	static class UPrimalItemResource_ApexDrop_Argentavis_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemResource_ApexDrop_Argentavis_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemResource_ApexDrop_Argentavis_C;

}

