#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemAmmo_Boulder_Fire

#include "Basic.hpp"

#include "PrimalItemAmmo_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemAmmo_Boulder_Fire.PrimalItemAmmo_Boulder_Fire_C
// 0x0000 (0x0B60 - 0x0B60)
class UPrimalItemAmmo_Boulder_Fire_C final : public UPrimalItemAmmo_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemAmmo_Boulder_Fire_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemAmmo_Boulder_Fire_C")
	}
	static class UPrimalItemAmmo_Boulder_Fire_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemAmmo_Boulder_Fire_C>();
	}
};
DUMPER7_ASSERTS_UPrimalItemAmmo_Boulder_Fire_C;

}

