#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StatsPanel

#include "Basic.hpp"


namespace SDK::Params
{

// Function StatsPanel.StatsPanel_C.ExecuteUbergraph_StatsPanel
// 0x0004 (0x0004 - 0x0000)
struct StatsPanel_C_ExecuteUbergraph_StatsPanel final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_StatsPanel_C_ExecuteUbergraph_StatsPanel;

}

