#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TekBunker_FunctionLib

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TekBunker_FunctionLib.TekBunker_FunctionLib_C
// 0x0000 (0x0030 - 0x0030)
class UTekBunker_FunctionLib_C final : public UObject_WithWorldContext
{
public:
	void ByteCoordinatesToVectorCoordinates(TArray<uint8>& Bytes, struct FVector* CoordinatesVector);
	void ContainsAllStrings(TArray<class FString>& Strings, const class FString& StringToCheck, class FString* RemainingString);
	void FindVisibleWidget(TArray<class UWidget*>& FromWidgets, class UWidget** VisibleWidget, bool* FoundVisibleWidget);
	void GetActorClass(class FName Name_0, class UClass** Class_0);
	void GetCraftableAmountForItem(class UPrimalItem* Item, class UPrimalInventoryComponent* Inventory, int32* CanCraftAmount);
	void GetDirectionFromVector(const struct FVector& Vector, class FName* Direction);
	void GetDirectlyAdjacentModuleCoordinates(const struct FVector& Coordinates, TArray<struct FVector>& ExistingModules, TArray<struct FVector>* AdjacentModulesCoordinates);
	void GetDrillModID(int64* modId);
	void GetJsonSettingKeys(class FString* UpgradeNameKey, class FString* DisabledTiersKey, class FString* EffectivenessMultipliersKey, class FString* UpgradeItemKey);
	void GetLayoutCCA(class AActor** CCA, bool* CCAValid);
	void GetOffsetFromDirection(class FName Direction, struct FVector* Offset);
	void GetPlayerOwnsTekDrillOrLostColony(class APlayerController* Player, bool* OwnsEither);
	void GetPlayerOwnsTekDrillOrLostColonyAndShowPrompt(class APlayerController* Player, bool* OwnsTekDrill);
	void GetTeamAllegiance(class APrimalCharacter* Character, int32 OtherTeam, bool* SameTribe, bool* Allies, bool* Enemies);
	void GetTekDrillWidgetClass(class FName Name_0, class UClass** Class_0);
	void IsActorObstruction(class AActor* Actor, class UPrimitiveComponent* Component, ECollisionChannel ForChannel, bool* IsObstruction);
	void IsModuleWithinBounds(const struct FVector& ModuleCoordinates, const struct FVector& PositiveBounds, const struct FVector& NegativeBounds, bool* WithinBounds);
	void ModuleCoordinatesToOffsets(const struct FVector& Coordinates, struct FVector* Offsets);
	void ModuleCoordinatesToWorldLocation(const struct FVector& Coordinates, class AActor* ForStructure, struct FVector* WorldLocation);
	void OffsetsToModuleCoordinates(const struct FVector& Offsets, struct FVector* Coordinates);
	void RealLocationToModuleCoordinates(const struct FVector& Location, class AActor* ForStructure, struct FVector* ModuleCoordinates, bool* IsWithinBounds);
	void ShowPrompt(class APlayerController* Player);
	void VectorCoordinatesToByteCoordinates(const struct FVector& VectorCoordinates, TArray<uint8>* Bytes);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TekBunker_FunctionLib_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TekBunker_FunctionLib_C")
	}
	static class UTekBunker_FunctionLib_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTekBunker_FunctionLib_C>();
	}
};
DUMPER7_ASSERTS_UTekBunker_FunctionLib_C;

}

