#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_DiscoveryShelve

#include "Basic.hpp"

#include "UI_DiscoveryShelve_classes.hpp"
#include "UI_DiscoveryShelve_parameters.hpp"


namespace SDK
{

// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.AddViewAllModSlot
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_DiscoveryShelve_C::AddViewAllModSlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "AddViewAllModSlot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.BndEvt__UI_HorizontalModList_UI_Button_ScrollToLeft_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature
// (BlueprintEvent)

void UUI_DiscoveryShelve_C::BndEvt__UI_HorizontalModList_UI_Button_ScrollToLeft_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "BndEvt__UI_HorizontalModList_UI_Button_ScrollToLeft_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.BndEvt__UI_HorizontalModList_UI_Button_ScrollToRight_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature
// (BlueprintEvent)

void UUI_DiscoveryShelve_C::BndEvt__UI_HorizontalModList_UI_Button_ScrollToRight_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "BndEvt__UI_HorizontalModList_UI_Button_ScrollToRight_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_DiscoveryShelve_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.Create
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FCFCoreMod>&              ServerMods                                             (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_DiscoveryShelve_C::Create(TArray<struct FCFCoreMod>& ServerMods)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "Create");

	Params::UI_DiscoveryShelve_C_Create Parms{};

	Parms.ServerMods = std::move(ServerMods);

	UObject::ProcessEvent(Func, &Parms);

	ServerMods = std::move(Parms.ServerMods);
}


// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.EmptyShelve
// (BlueprintCallable, BlueprintEvent)

void UUI_DiscoveryShelve_C::EmptyShelve()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "EmptyShelve");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.ExecuteUbergraph_UI_DiscoveryShelve
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_DiscoveryShelve_C::ExecuteUbergraph_UI_DiscoveryShelve(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "ExecuteUbergraph_UI_DiscoveryShelve");

	Params::UI_DiscoveryShelve_C_ExecuteUbergraph_UI_DiscoveryShelve Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.FadeDirections
// (BlueprintCallable, BlueprintEvent)

void UUI_DiscoveryShelve_C::FadeDirections()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "FadeDirections");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.LeftIn
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_DiscoveryShelve_C::LeftIn(bool Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "LeftIn");

	Params::UI_DiscoveryShelve_C_LeftIn Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_DiscoveryShelve_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "PreConstruct");

	Params::UI_DiscoveryShelve_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.RightIn
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_DiscoveryShelve_C::RightIn(bool Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "RightIn");

	Params::UI_DiscoveryShelve_C_RightIn Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.SortInstalledAndPremiumLast
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_DiscoveryShelve_C::SortInstalledAndPremiumLast()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "SortInstalledAndPremiumLast");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_DiscoveryShelve.UI_DiscoveryShelve_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_DiscoveryShelve_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_DiscoveryShelve_C", "Tick");

	Params::UI_DiscoveryShelve_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

