#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Discovery

#include "Basic.hpp"

#include "UI_Discovery_classes.hpp"
#include "UI_Discovery_parameters.hpp"


namespace SDK
{

// Function UI_Discovery.UI_Discovery_C.BndEvt__UI_Discovery_UI_Button_Ark_ViewMod_1_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature
// (BlueprintEvent)

void UUI_Discovery_C::BndEvt__UI_Discovery_UI_Button_Ark_ViewMod_1_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "BndEvt__UI_Discovery_UI_Button_Ark_ViewMod_1_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.BndEvt__UI_Discovery_UI_Button_Ark_ViewMod_2_K2Node_ComponentBoundEvent_6_OnClick__DelegateSignature
// (BlueprintEvent)

void UUI_Discovery_C::BndEvt__UI_Discovery_UI_Button_Ark_ViewMod_2_K2Node_ComponentBoundEvent_6_OnClick__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "BndEvt__UI_Discovery_UI_Button_Ark_ViewMod_2_K2Node_ComponentBoundEvent_6_OnClick__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.BndEvt__UI_Discovery_UI_Button_Ark_ViewMod_K2Node_ComponentBoundEvent_4_OnClick__DelegateSignature
// (BlueprintEvent)

void UUI_Discovery_C::BndEvt__UI_Discovery_UI_Button_Ark_ViewMod_K2Node_ComponentBoundEvent_4_OnClick__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "BndEvt__UI_Discovery_UI_Button_Ark_ViewMod_K2Node_ComponentBoundEvent_4_OnClick__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.BndEvt__UI_Discovery_UI_Button_Back_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature
// (BlueprintEvent)

void UUI_Discovery_C::BndEvt__UI_Discovery_UI_Button_Back_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "BndEvt__UI_Discovery_UI_Button_Back_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.BndEvt__UI_Discovery_UI_Button_Options_K2Node_ComponentBoundEvent_3_OnClick__DelegateSignature
// (BlueprintEvent)

void UUI_Discovery_C::BndEvt__UI_Discovery_UI_Button_Options_K2Node_ComponentBoundEvent_3_OnClick__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "BndEvt__UI_Discovery_UI_Button_Options_K2Node_ComponentBoundEvent_3_OnClick__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.Build Discovery Tab
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::Build_Discovery_Tab()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "Build Discovery Tab");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Discovery_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.ConstructDiscovery
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::ConstructDiscovery()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "ConstructDiscovery");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.Create HighestRated
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::Create_HighestRated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "Create HighestRated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.Create Latest
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::Create_Latest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "Create Latest");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.Create Premium Shelve
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::Create_Premium_Shelve()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "Create Premium Shelve");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.CreateCarousel
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::CreateCarousel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "CreateCarousel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.CreateCategory
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::CreateCategory()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "CreateCategory");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.CreateTrending
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::CreateTrending()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "CreateTrending");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.CustomEvent
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FModsHighlightsV2&         mods                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Discovery_C::CustomEvent(const struct FModsHighlightsV2& mods)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "CustomEvent");

	Params::UI_Discovery_C_CustomEvent Parms{};

	Parms.mods = std::move(mods);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Discovery.UI_Discovery_C.DestroySpotlightPreview
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::DestroySpotlightPreview()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "DestroySpotlightPreview");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.DestroySpotlightPreviewTempCopy
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::DestroySpotlightPreviewTempCopy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "DestroySpotlightPreviewTempCopy");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.ExecuteUbergraph_UI_Discovery
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Discovery_C::ExecuteUbergraph_UI_Discovery(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "ExecuteUbergraph_UI_Discovery");

	Params::UI_Discovery_C_ExecuteUbergraph_UI_Discovery Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Discovery.UI_Discovery_C.GetControlSizeBox
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USizeBox**                        SizeBoxForControls                                     (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Discovery_C::GetControlSizeBox(class USizeBox** SizeBoxForControls)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "GetControlSizeBox");

	Params::UI_Discovery_C_GetControlSizeBox Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SizeBoxForControls != nullptr)
		*SizeBoxForControls = Parms.SizeBoxForControls;
}


// Function UI_Discovery.UI_Discovery_C.GetOptionsButton
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUI_Button_Ark_Global_Base_C**    OptionsButton                                          (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Discovery_C::GetOptionsButton(class UUI_Button_Ark_Global_Base_C** OptionsButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "GetOptionsButton");

	Params::UI_Discovery_C_GetOptionsButton Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OptionsButton != nullptr)
		*OptionsButton = Parms.OptionsButton;
}


// Function UI_Discovery.UI_Discovery_C.IMG_ShowcasePreview_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UImage*                           IMG_ShowcasePreview_0                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Discovery_C::IMG_ShowcasePreview_Event(class UImage* IMG_ShowcasePreview_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "IMG_ShowcasePreview_Event");

	Params::UI_Discovery_C_IMG_ShowcasePreview_Event Parms{};

	Parms.IMG_ShowcasePreview_0 = IMG_ShowcasePreview_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Discovery.UI_Discovery_C.NextShowcase
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::NextShowcase()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "NextShowcase");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.OnErrorGetModHighlights
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FCFCoreError&              Error                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Discovery_C::OnErrorGetModHighlights(const struct FCFCoreError& Error)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "OnErrorGetModHighlights");

	Params::UI_Discovery_C_OnErrorGetModHighlights Parms{};

	Parms.Error = std::move(Error);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Discovery.UI_Discovery_C.OnErrorGetModsHighlightRest
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FCFCoreError&              Error                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Discovery_C::OnErrorGetModsHighlightRest(const struct FCFCoreError& Error)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "OnErrorGetModsHighlightRest");

	Params::UI_Discovery_C_OnErrorGetModsHighlightRest Parms{};

	Parms.Error = std::move(Error);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Discovery.UI_Discovery_C.OnModHighlightsFound
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FModsHighlightsV2&         mods                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UUI_Discovery_C::OnModHighlightsFound(const struct FModsHighlightsV2& mods)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "OnModHighlightsFound");

	Params::UI_Discovery_C_OnModHighlightsFound Parms{};

	Parms.mods = std::move(mods);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Discovery.UI_Discovery_C.OnPressVieAllPurchased
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::OnPressVieAllPurchased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "OnPressVieAllPurchased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.OnPressViewAllLatest
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::OnPressViewAllLatest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "OnPressViewAllLatest");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.OnPressViewAllOnMostDL
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::OnPressViewAllOnMostDL()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "OnPressViewAllOnMostDL");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.OpenSpotlight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int64                                   SpotlightID                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Discovery_C::OpenSpotlight(int64 SpotlightID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "OpenSpotlight");

	Params::UI_Discovery_C_OpenSpotlight Parms{};

	Parms.SpotlightID = SpotlightID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Discovery.UI_Discovery_C.OpenSpotlightShowcasePage
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::OpenSpotlightShowcasePage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "OpenSpotlightShowcasePage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.ReloadPage
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::ReloadPage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "ReloadPage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.ResetAllFilters
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::ResetAllFilters()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "ResetAllFilters");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.ReturnFromModPage
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::ReturnFromModPage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "ReturnFromModPage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.SequenceEvent__ENTRYPOINTUI_Discovery
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UImage*                           IMG_ShowcasePreview_0                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Discovery_C::SequenceEvent__ENTRYPOINTUI_Discovery(class UImage* IMG_ShowcasePreview_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "SequenceEvent__ENTRYPOINTUI_Discovery");

	Params::UI_Discovery_C_SequenceEvent__ENTRYPOINTUI_Discovery Parms{};

	Parms.IMG_ShowcasePreview_0 = IMG_ShowcasePreview_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Discovery.UI_Discovery_C.SetToNewCurrentShowcaseSlot
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUI_ShowcaseSlot_C*               NewSlot                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Discovery_C::SetToNewCurrentShowcaseSlot(class UUI_ShowcaseSlot_C* NewSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "SetToNewCurrentShowcaseSlot");

	Params::UI_Discovery_C_SetToNewCurrentShowcaseSlot Parms{};

	Parms.NewSlot = NewSlot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Discovery.UI_Discovery_C.Start Progress
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::Start_Progress()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "Start Progress");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.StartDiscoveryOnReady
// (BlueprintCallable, BlueprintEvent)

void UUI_Discovery_C::StartDiscoveryOnReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "StartDiscoveryOnReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Discovery.UI_Discovery_C.UpdateCarouselFromMod
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUI_ShowcaseSlot_C*               ShowcaseSlot                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Discovery_C::UpdateCarouselFromMod(class UUI_ShowcaseSlot_C* ShowcaseSlot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Discovery_C", "UpdateCarouselFromMod");

	Params::UI_Discovery_C_UpdateCarouselFromMod Parms{};

	Parms.ShowcaseSlot = ShowcaseSlot;

	UObject::ProcessEvent(Func, &Parms);
}

}

