#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_GoToBrowseAllMods

#include "Basic.hpp"

#include "UI_GoToBrowseAllMods_classes.hpp"
#include "UI_GoToBrowseAllMods_parameters.hpp"


namespace SDK
{

// Function UI_GoToBrowseAllMods.UI_GoToBrowseAllMods_C.ApplyThemeSettingsToAll
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_GoToBrowseAllMods_C::ApplyThemeSettingsToAll()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_GoToBrowseAllMods_C", "ApplyThemeSettingsToAll");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_GoToBrowseAllMods.UI_GoToBrowseAllMods_C.BndEvt__UI_GoToBrowseAllMods_UI_Button_Ark_Global_Install_K2Node_ComponentBoundEvent_2_OnReleased__DelegateSignature
// (BlueprintEvent)

void UUI_GoToBrowseAllMods_C::BndEvt__UI_GoToBrowseAllMods_UI_Button_Ark_Global_Install_K2Node_ComponentBoundEvent_2_OnReleased__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_GoToBrowseAllMods_C", "BndEvt__UI_GoToBrowseAllMods_UI_Button_Ark_Global_Install_K2Node_ComponentBoundEvent_2_OnReleased__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_GoToBrowseAllMods.UI_GoToBrowseAllMods_C.ExecuteUbergraph_UI_GoToBrowseAllMods
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_GoToBrowseAllMods_C::ExecuteUbergraph_UI_GoToBrowseAllMods(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_GoToBrowseAllMods_C", "ExecuteUbergraph_UI_GoToBrowseAllMods");

	Params::UI_GoToBrowseAllMods_C_ExecuteUbergraph_UI_GoToBrowseAllMods Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

