#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Tag_PreviewSale

#include "Basic.hpp"

#include "CFCoreUIWidget_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Tag_PreviewSale.UI_Tag_PreviewSale_C
// 0x0010 (0x0848 - 0x0838)
class UUI_Tag_PreviewSale_C final : public UCFCoreUIWidget_C
{
public:
	class UImage*                                 IMG_BackOutlineforBackground;                      // 0x0838(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TEXT_InsideText;                                   // 0x0840(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void UpdateText(const class FText& InText);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_Tag_PreviewSale_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_Tag_PreviewSale_C")
	}
	static class UUI_Tag_PreviewSale_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Tag_PreviewSale_C>();
	}
};
DUMPER7_ASSERTS_UUI_Tag_PreviewSale_C;

}

