#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Underwater_Gate_Tek

#include "Basic.hpp"

#include "Door_Tek_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Underwater_Gate_Tek.Underwater_Gate_Tek_C
// 0x0010 (0x0CF0 - 0x0CE0)
class AUnderwater_Gate_Tek_C : public ADoor_Tek_Base_C
{
public:
	class UBoxComponent*                          StructurePreventionBox;                            // 0x0CE0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          InteractionBox;                                    // 0x0CE8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Underwater_Gate_Tek_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Underwater_Gate_Tek_C")
	}
	static class AUnderwater_Gate_Tek_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AUnderwater_Gate_Tek_C>();
	}
};
DUMPER7_ASSERTS_AUnderwater_Gate_Tek_C;

}

