#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MilestonesRewardEntry

#include "Basic.hpp"

#include "W_MilestonesRewardEntry_classes.hpp"
#include "W_MilestonesRewardEntry_parameters.hpp"


namespace SDK
{

// Function W_MilestonesRewardEntry.W_MilestonesRewardEntry_C.SetReward
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UW_MilestonesRewardEntry_C::SetReward(class UObject* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MilestonesRewardEntry_C", "SetReward");

	Params::W_MilestonesRewardEntry_C_SetReward Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);
}

}

