#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MilestonesRewardEntry

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_MilestonesRewardEntry.W_MilestonesRewardEntry_C
// 0x0010 (0x0388 - 0x0378)
class UW_MilestonesRewardEntry_C final : public UPrimalUserWidget
{
public:
	class UImage*                                 Image_3;                                           // 0x0378(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCustomButtonWidget*                    SkillTreeMenuButton;                               // 0x0380(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetReward(class UObject* Object);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_MilestonesRewardEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_MilestonesRewardEntry_C")
	}
	static class UW_MilestonesRewardEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_MilestonesRewardEntry_C>();
	}
};
DUMPER7_ASSERTS_UW_MilestonesRewardEntry_C;

}

