#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SkillPanel

#include "Basic.hpp"

#include "W_SkillPanel_classes.hpp"
#include "W_SkillPanel_parameters.hpp"


namespace SDK
{

// Function W_SkillPanel.W_SkillPanel_C.SelectSkill
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FName&                      SkillID                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 MouseCursorLocation                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FPrimalSkill&              PrimalSkill                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_SkillPanel_C::SelectSkill(const class FName& SkillID, const struct FVector2D& MouseCursorLocation, const struct FPrimalSkill& PrimalSkill)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_SkillPanel_C", "SelectSkill");

	Params::W_SkillPanel_C_SelectSkill Parms{};

	Parms.SkillID = SkillID;
	Parms.MouseCursorLocation = std::move(MouseCursorLocation);
	Parms.PrimalSkill = std::move(PrimalSkill);

	UObject::ProcessEvent(Func, &Parms);
}

}

