#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeapGun_Impacts

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WeapGun_Impacts.WeapGun_Impacts_C
// 0x0008 (0x08A0 - 0x0898)
class AWeapGun_Impacts_C : public AShooterImpactEffect
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0898(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WeapGun_Impacts_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WeapGun_Impacts_C")
	}
	static class AWeapGun_Impacts_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapGun_Impacts_C>();
	}
};
DUMPER7_ASSERTS_AWeapGun_Impacts_C;

}

