#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeapChainsaw_Impacts

#include "Basic.hpp"

#include "MeleeFist_Impacts_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WeapChainsaw_Impacts.WeapChainsaw_Impacts_C
// 0x0000 (0x08A0 - 0x08A0)
class AWeapChainsaw_Impacts_C final : public AMeleeFist_Impacts_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WeapChainsaw_Impacts_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WeapChainsaw_Impacts_C")
	}
	static class AWeapChainsaw_Impacts_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapChainsaw_Impacts_C>();
	}
};
DUMPER7_ASSERTS_AWeapChainsaw_Impacts_C;

}

