#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WoodHarvestComponent

#include "Basic.hpp"

#include "AttackHarvestComponent_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WoodHarvestComponent.WoodHarvestComponent_C
// 0x0000 (0x0228 - 0x0228)
class UWoodHarvestComponent_C final : public UAttackHarvestComponent_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WoodHarvestComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WoodHarvestComponent_C")
	}
	static class UWoodHarvestComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWoodHarvestComponent_C>();
	}
};
DUMPER7_ASSERTS_UWoodHarvestComponent_C;

}

